export default {
    //  base的全部事件
    PHOTO_BASE_CHANGE: 'PHOTO_BASE_CHANGE',
    PHOTO_BASE_INIT: 'PHOTO_BASE_INIT',
    PHOTO_PARAM_DRAG_STATE: 'PHOTO_PARAM_DRAG_STATE',
    PHOTO_BASE_BACK_TO_ORIGIN: 'PHOTO_BASE_BACK_TO_ORIGIN',
    PHOTO_BASE_COUNT_CHANGE: 'PHOTO_BASE_COUNT_CHANGE',
    PHOTO_BASE_CLEAR_COUNT: 'PHOTO_BASE_CLEAR_COUNT',
    PHOTO_BASE_CHANGE_IMG_SRC: 'PHOTO_BASE_CHANGE_IMG_SRC',
    PHOTO_BASE_HISTORY_RENDER: 'PHOTO_BASE_HISTORY_RENDER',
    PHOTO_BASE_CLEAR_ALL_CONFIG: 'PHOTO_BASE_CLEAR_ALL_CONFIG',

    // 旋转
    PHOTO_ROTATE_REVISE_CHANGE: 'PHOTO_ROTATE_REVISE_CHANGE', // 旋转的拖拽
    PHOTO_ROTATE_GENERATE_IMG: 'PHOTO_ROTATE_GENERATE_IMG', // 是否生成正图
    PHOTO_ROTATE_HISTORY_RENDER: 'PHOTO_ROTATE_HISTORY_RENDER', // 旋转-回退
    PHOTO_ROTATE_BACK_TO_ORIGIN: 'PHOTO_ROTATE_BACK_TO_ORIGIN', // 是不是回退到原图
    PHOTO_ROTATE_KEEP_CONFIG: 'PHOTO_ROTATE_KEEP_CONFIG', // 每次旋转之后保存的配置 专门用于在旋转模块的下载

    PHOTO_ORIGIN_KEY: 'PHOTO_ORIGIN_KEY', // 源图key
    PHOTO_ORIGIN_IMAGE: 'PHOTO_ORIGIN_IMAGE', // 源图
    PHOTO_ORIGIN_IMAGE_SHOT: 'PHOTO_ORIGIN_IMAGE_SHOT', // 原图的缩略图
    PHOTO_ORIGIN_IMAGE_SIZE: 'PHOTO_ORIGIN_IMAGE_SIZE', // 源图尺寸信息
    PHOTO_SET_ORIGIN_IMAGE_INFO: 'PHOTO_SET_ORIGIN_IMAGE_INFO', // 设置原图和size
    PHOTO_IS_UPLOAD_IMAGE: 'PHOTO_IS_UPLOAD_IMAGE', // 是否上传了图片
    PHOTO_RE_UPLOAD_IMAGE: 'PHOTO_RE_UPLOAD_IMAGE', // 重新上传消息通知
    PHOTO_NAV_LIST: 'PHOTO_NAV_LIST', // 导航栏列表
    PHOTO_NAV: 'PHOTO_NAV', // 导航栏
    PHOTO_NAV_PANEL: 'PHOTO_NAV_PANEL', // 导航栏仪表板
    PHOT_NAV_CAN_CHANGE: 'PHOT_NAV_CAN_CHANGE', // 是否可以切换

    PHOTO_SCENE_INIT: 'PHOTO_SCENE_INIT', // 初始化场景数据
    PHOTO_SCENE_SIZE_CHANGE: 'PHOTO_SCENE_SIZE_CHANGE', // 改变场景宽高大小

    PHOTO_PAGE_ADD: 'PHOTO_PAGE_ADD', // 添加页面
    PHOTO_PAGE_SAVE: 'PHOTO_PAGE_SAVE', // 保存页面

    PHOTO_SIDE_BAR: 'PHOTO_SIDE_BAR', // 侧边栏

    PHOTO_HISTORY_INIT: 'PHOTO_HISTORY_INIT', // 初始化历史记录
    PHOTO_HISTORY_SET: 'PHOTO_HISTORY_SET', // 设置后退、前进按钮状态
    PHOTO_HISTORY_BACK: 'PHOTO_HISTORY_BACK', // 点击后退
    PHOTO_HISTORY_FORWORD: 'PHOTO_HISTORY_FORWORD', // 点击前进
    PHOTO_HISTORY_UNDO_TO_ORIGINAL: 'PHOTO_HISTORY_UNDO_TO_ORIGINAL', // 恢复到原图

    PHOTO_TOOBAR_ORIGINAL: 'PHOTO_TOOBAR_ORIGINAL', // 工具条对比原图
    PHOTO_TOOL_CROP: 'PHOTO_TOOL_CROP', // 裁切
    PHOTO_TOOL_CROP_CHANGE_EVENT: 'PHOTO_TOOL_CROP_CHANGE_EVENT', // 裁切参数改变

    // 滤镜
    PHOTO_FILTER_SNAPSHOT_CHANGE: 'PHOTO_FILTER_SNAPSHOT_CHANGE', // 快照改变
    PHOTO_FILTER_INTENSITY_CHANGE: 'PHOTO_FILTER_INTENSITY_CHANGE', // 强度改变
    PHOTO_FILTER_GL_CANVAS_CHANGE: 'PHOTO_FILTER_GL_CANVAS_CHANGE',
    PHOTO_FILTER_IS_BACK_TO_ORIGIN: 'PHOTO_FILTER_IS_BACK_TO_ORIGIN', // 回到原图标识
    PHOTO_FILTER_PRIMARY_IMG_CHANGE: 'PHOTO_FILTER_PRIMARY_IMG_CHANGE', // 效果原图
    PHOTO_FILTER_FIRST_ADD_HISTORY: 'PHOTO_FILTER_FIRST_ADD_HISTORY', // 是不是第一次添加历史
    PHOTO_FILTER_HISTORY_RENDER: 'PHOTO_FILTER_HISTORY_RENDER', // 历史回退render方法

    // 选中元素
    PHOTO_ELEMENT_SELECT: 'PHOTO_ELEMENT_SELECT',
    // 判断用户是不是按住了ctrl
    PHOTO_CTRL_STATE_CHANGE: 'PHOTO_CTRL_STATE_CHANGE',
    //
    PHOTO_ELEMENT_COPY: 'PHOTO_ELEMENT_COPY',
    //
    PHOTO_ELEMENT_PASTE: 'PHOTO_ELEMENT_PASTE',

    // workspace
    PHOTO_SCENE_CLEAR: 'PHOTO_SCENE_CLEAR',

    PHOTO_ELEMENTS_HISTORY_RENDER: 'PHOTO_ELEMENTS_HISTORY_RENDER', // 组件历史记录

    PHOTO_CROP_HISTORY_RENDER: 'PHOTO_CROP_HISTORY_RENDER', // 裁切历史记录

    PHOTO_SCENE_IS_HISTORY_CHANGE_NAV: 'PHOTO_SCENE_IS_HISTORY_CHANGE_NAV' // 判断是不是历史回退导致的菜单切换
}
