export default {
    LAYOUT_NAV: 'LAYOUT_NAV',
    LAYOUT_NAV_LIST: 'LAYOUT_NAV_LIST',
    LAYOUT_NAV_PANEL: 'LAYOUT_NAV_PANEL',
    LAYOUT_MATERIAL: 'LAYOUT_MATERIAL',
    LAYOUT_NAV_UPLOAD_RELOAD: 'LAYOUT_NAV_UPLOAD_RELOAD',
    LAYOUT_NAV_UPLOAD_QRCODE: 'LAYOUT_NAV_UPLOAD_QRCODE',
    LAYOUT_NAV_UPLOAD_MANAGE: 'LAYOUT_NAV_UPLOAD_MANAGE',
    LAYOUT_EDITOR_SIZE: 'LAYOUT_EDITOR_SIZE',
    LAYOUT_LAYER: 'LAYOUT_LAYER',
    GRID_SET: 'GRID_SET',
    LAYOUT_CONTEXT_MENU: 'LAYOUT_CONTEXT_MENU',
    LAYOUT_LOGO: 'LAYOUT_LOGO',
    LAYOUT_PREVIEW: 'LAYOUT_PREVIEW',
    LAYOUT_WORKSPACESCROLL: 'LAYOUT_WORKSPACESCROLL',

    GUIDE_LINE_INIT: 'GUIDE_LINE_INIT',
    GUIDE_LINE_TOP: 'GUIDE_LINE_TOP',
    GUIDE_LINE_CENTERY: 'GUIDE_LINE_CENTERY',
    GUIDE_LINE_BOTTOM: 'GUIDE_LINE_BOTTOM',
    GUIDE_LINE_LEFT: 'GUIDE_LINE_LEFT',
    GUIDE_LINE_CENTERX: 'GUIDE_LINE_CENTERX',
    GUIDE_LINE_RIGHT: 'GUIDE_LINE_RIGHT',
    GUIDE_LINE_CLEAR: 'GUIDE_LINE_CLEAR',
    GUIDE_SPACING_ADD: 'GUIDE_SPACING_ADD',
    GUIDE_SPACING_CLEAR: 'GUIDE_SPACING_CLEAR',
    GUIDE_EQUAL_WIDTH: 'GUIDE_EQUAL_WIDTH',
    GUIDE_EQUAL_HEIGHT: 'GUIDE_EQUAL_HEIGHT',
    GUIDE_EQUAL_WIDTH_HEIGHT_CLEAR: 'GUIDE_EQUAL_WIDTH_HEIGHT_CLEAR',

    RULER_SHOW: 'RULER_SHOW',
    RULER_CLEAR: 'RULER_CLEAR',
    RULER_TOP_ADD: 'RULER_TOP_ADD',
    RULER_LEFT_ADD: 'RULER_LEFT_ADD',
    RULER_TOP_DELETE: 'RULER_TOP_DELETE',
    RULER_LEFT_DELETE: 'RULER_LEFT_DELETE',
    RULER_ADD: 'RULER_ADD',

    SCENE_INIT: 'SCENE_INIT',
    SCENE_EDIT_COMPLETE_EVENT: 'SCENE_EDIT_COMPLETE_EVENT',
    SCENE2_INIT: 'SCENE2_INIT',
    SCENE2_EDIT_COMPLETE_EVENT: 'SCENE2_EDIT_COMPLETE_EVENT',
    SCENE3_INIT: 'SCENE3_INIT',
    SCENE3_EDIT_COMPLETE_EVENT: 'SCENE3_EDIT_COMPLETE_EVENT',
    CACHE_IMAGE: 'CACHE_IMAGE',
    CLEAR_CACHE_IMAGE: 'CLEAR_CACHE_IMAGE',
    GET_NO_WATERMARK_COVER: 'GET_NO_WATERMARK_COVER',
    WATERMARK_COVER_CHANGE: 'WATERMARK_COVER_CHANGE',
    SCENE_BACKGROUND_PHONE_UPLOAD_FINISH: 'SCENE_BACKGROUND_PHONE_UPLOAD_FINISH',
    SCENE_IS_NEED_INIT_COMBINE_BOX: 'SCENE_IS_NEED_INIT_COMBINE_BOX', // 是否生成组合框
    SCENE_SIDERBAR_MENU_OPTION: 'SCENE_SIDERBAR_MENU_OPTION',
    SCENE_SIDERBAR_MENU_OPTION_SHOW: 'SCENE_SIDERBAR_MENU_OPTION_SHOW',
    SCENE_TABLE_CLICK_TIMESTAMP: 'SCENE_TABLE_CLICK_TIMESTAMP', // 触发tableclick事件
    SCENE_TABLE_TABLE_MENU: 'SCENE_TABLE_TABLE_MENU', // table 触发右键menu
    SCENE_TABLE_TABLE_MENU_IN_CHANGE: 'SCENE_TABLE_TABLE_MENU_IN_CHANGE',
    SCENE_TABLE_STYLE_LAYER_CHANGE: 'SCENE_TABLE_STYLE_LAYER_CHANGE',

    PAGE_CHANGE: 'PAGE_CHANGE',
    PAGE_ADD: 'PAGE_ADD',
    PAGE_DELETE: 'PAGE_DELETE',
    PAGE_COPY: 'PAGE_COPY',
    PAGE_SAVE: 'PAGE_SAVE',
    ART_PAGE_SAVE: 'ART_PAGE_SAVE',

    HISTORY_SET: 'HISTORY_SET',
    HISTORY_BACK: 'HISTORY_BACK',
    HISTORY_FORWORD: 'HISTORY_FORWORD',
    HISTORY_NO_FLAG: 'HISTORY_NO_FLAG',

    ELEMENT_SELECT: 'ELEMENT_SELECT',
    ELEMENT_COPY: 'ELEMENT_COPY',
    ELEMENT_PASTE: 'ELEMENT_PASTE',

    PRODUCT_CATEGORY_LEVEL1_LIST: 'PRODUCT_CATEGORY_LEVEL1_LIST',
    PRODUCT_CATEGORY_TEMPLATE: 'PRODUCT_CATEGORY_TEMPLATE',
    PRODUCT_TYPE: 'PRODUCT_TYPE',
    PRODUCT_ID: 'PRODUCT_ID',
    PRODUCT_CATEGORY_TCOULD_LIST: 'PRODUCT_CATEGORY_TCOULD_LIST',
    PRODUCT_CATEGORY_PUZZLE_LIST: 'PRODUCT_CATEGORY_PUZZLE_LIST',

    USER_SET: 'USER_SET',
    USER_PHONE_CHANGE: 'USER_PHONE_CHANGE',
    USER_WATER_RIGHT: 'USER_WATER_RIGHT',
    USER_UPLOAD_LIMIT_RIGHT: 'USER_UPLOAD_LIMIT_RIGHT',

    PAGE_ORDER_CHANGED: 'PAGE_ORDER_CHANGED',

    FONT_STYLE_INIT: 'FONT_STYLE_INIT',
    FONT_STYLE_SELECTED: 'FONT_STYLE_SELECTED',
    FONT_STYLE_LAYER: 'FONT_STYLE_LAYER',
    FONT_TEXT_LAYER: 'FONT_TEXT_LAYER',
    FONT_STYLE_ISLOAD: 'FONT_STYLE_ISLOAD',
    TEXT_THREED_STYLE_LAYER: 'TEXT_THREED_STYLE_LAYER',
    TEXT_THREED_FONT_LAYER: 'TEXT_THREED_FONT_LAYER', // 设置3D文字字体选择面板显示与否
    TEXT_THREED_TEXTURE_LAYER: 'TEXT_THREED_TEXTURE_LAYER',

    GIF_WOKER_CHOOSE: 'GIF_WOKER_CHOOSE',
    GIG_QUALITY_CHOOSE: 'GIG_QUALITY_CHOOSE',

    CTRL_STATE_CHANGE: 'CTRL_STATE_CHANGE',
    CHANGE_UPLOAD_TAG: 'CHANGE_UPLOAD_TAG',

    EXPRESS_MODE: 'EXPRESS_MODE',
    PUZZLE_MODE: 'PUZZLE_MODE',
    EXPRESS_HEAD_MENU: 'EXPRESS_HEAD_MENU',

    SIGN_SUBSCRIBE_STATUS: 'SIGN_SUBSCRIBE_STATUS',
    SIGN_SHOW_CROP: 'SIGN_SHOW_CROP',
    SIGN_INFO: 'SIGN_INFO',
    SIGN_USER: 'SIGN_USER',
    SIGN_RESULT: 'SIGN_RESULT',
    SIGN_ATTENTION: 'SIGN_ATTENTION',

    MATCH_CATEGORY: 'MATCH_CATEGORY',
    SCENE_SIZE_CHANGE: 'SCENE_SIZE_CHANGE',
    ADD_BATCH_PRODUCT_TEMPLATE_RELATION: 'ADD_BATCH_PRODUCT_TEMPLATE_RELATION',

    QRCODE_NAV: 'QRCODE_NAV',
    QRCODE_TEMPLATE_LIST_FILTER: 'QRCODE_TEMPLATE_LIST_FILTER',
    QRCODE_TEMPLATE_USE: 'QRCODE_TEMPLATE_USE',
    QRCODE_TEMPLATE_USE_CLEAR: 'QRCODE_TEMPLATE_USE_CLEAR',
    QRCODE_UPLOAD_BY_PHONE_AND_KEYBOARD: 'QRCODE_UPLOAD_BY_PHONE_AND_KEYBOARD',
    QRCODE_UPLOAD_RELOAD: 'QRCODE_UPLOAD_RELOAD',
    QRCODE_SELECTED_TEMPLATE_TYPE: 'QRCODE_SELECTED_TEMPLATE_TYPE',
    QRCODE_KEY: 'QRCODE_KEY',
    QRCODE_KEY_CLEAR: 'QRCODE_KEY_CLEAR',
    QRCODE_SCENE_JSON: 'QRCODE_SCENE_JSON',

    AIMATTING_MATTING_IMAGE: 'AIMATTING_MATTING_IMAGE',
    AIMATTING_MATTING_SCALE: 'AIMATTING_MATTING_SCALE',
    AIMATTING_MATTING_OPEN_DRAG: 'AIMATTING_MATTING_OPEN_DRAG',
    AIMATTING_MATTING_PEN_MODE: 'AIMATTING_MATTING_PEN_MODE',
    AIMATTING_MATTING_UNDO: 'AIMATTING_MATTING_UNDO',
    AIMATTING_MATTING_REDO: 'AIMATTING_MATTING_REDO',
    AIMATTING_MATTING_PEN_WIDTH: 'AIMATTING_MATTING_PEN_WIDTH',
    AIMATTING_MATTING_SMOOTHNESS: 'AIMATTING_MATTING_SMOOTHNESS',
    AIMATTING_MATTING_FILL_COLOR: 'AIMATTING_MATTING_FILL_COLOR',
    AIMATTING_MATTING_STATUS: 'AIMATTING_MATTING_STATUS',

    MAIN_EDITOR_VIEW: 'MAIN_EDITOR_VIEW',
    MATERIAL_ITEM_PREVIEW: 'MATERIAL_ITEM_PREVIEW', // 素材预览
    MATERIAL_MORE_CHANGE: 'MATERIAL_MORE_CHANGE', // 素材更多 里面的条件显示
    MATERIAL_COLLECT_LIST_CHANGE: 'MATERIAL_COLLECT_LIST_CHANGE', // 是否刷新收藏列表
    MATERIAL_PREVIEW_AUTHOR_CHANGE: 'MATERIAL_PREVIEW_AUTHOR_CHANGE', // 控制素材库是否放大显示

    TEMPLATE_COLOR_PANEL: 'TEMPLATE_COLOR_PANEL', // 模板颜色面板信息
    TEMPLATE_COLOR_PANEL_COLOR_SELECTED: 'TEMPLATE_COLOR_PANEL_COLOR_SELECTED', // 模板颜色选择
    TEMPLATE_CONFIG: 'TEMPLATE_CONFIG', // 模板设置
    TEMPLATE_CATEGORY: 'TEMPLATE_CATEGORY', // 模板设置
    TEMPLATE_COLLECT_LIST_CHANGE: 'TEMPLATE_COLLECT_LIST_CHANGE', // 模板收藏改变

    TCLOUD_NAV: 'TCLOUD_NAV',
    TCLOUD_NAV_PANEL: 'TCLOUD_NAV_PANEL',
    TCLOUD_INIT: 'TCLOUD_INIT',

    PUZZLE_NAV: 'PUZZLE_NAV',
    PUZZLE_NAV_PANEL: 'PUZZLE_NAV_PANEL',
    PUZZLE_LAYOUT_MODE: 'PUZZLE_LAYOUT_MODE'
}
